#include <iostream>
#include <math.h>
#include <fstream>

using namespace std;
/*int plus (int c1,int c2,int c3);*/
/*void validation (string user,string pass);*/
//void f1(int br [],int x);
//void f1(int br[],int z);
//void f1(int br[][3]);
/*class c1{
	public:
		void mt1(){
			cout<<"bela ciao 	";
		}
		void mt2(){
			int ss[10];
			int *p;
			p=ss;
			p=p+9;
			for(int i=0;i<10;i++){
				cin>>ss[i];
}
			for(int i=0;i<10;i++){
			cout<<*p<<"\t";
			p--;
}
			
		}
};*/
/*void display(int ss[][3],int tt[][3]);
string login ();


string display1;
class project{
	public:
		void add(){
			int shayan1[3][3];
			int shayan2[3][3];
			cout<<"enter first numbers:"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cin>>shayan1[i][j];
				}
			}
			cout<<"-------------------"<<endl;
			cout<<"enter second numbers:"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cin>>shayan2[i][j];
				}
			}
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					shayan1[i][j]=shayan1[i][j]+shayan2[i][j];
				}
			}
			cout<<"-------------------"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cout<<shayan1[i][j]<<" ";
				}
			}
		};
		void differ(){
			int sr1[3][3];
			int sr2[3][3];
			cout<<"enter first numbers:"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cin>>sr1[i][j];
				}
			}
			cout<<"-------------------"<<endl;
			cout<<"enter second numbers:"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cin>>sr2[i][j];
				}
			}
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					sr1[i][j]=sr1[i][j]-sr2[i][j];
				}
			}
			cout<<"-------------------"<<endl;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					cout<<sr1[i][j]<<" ";
					
				}
			}
			
		}
		void error(){
			for(int i=3;i>0;i--){
				if(display1=="add"){
					project adding1;
					adding1.add();
				}
				if(display1=="differ"){
					project differing2;
					differing2.differ();
				}
				cout<<"Your answer is false!"<<"  Your remaining chances:"<<i<<endl;
				cin>>display1;
				
			}
			cout<<endl<<"xxxxxxxxxxxxxxxxxxxxxxxxxxx"<<endl<<"x Your  access has denied x"<<endl<<"xxxxxxxxxxxxxxxxxxxxxxxxxxx"<<endl;
		}
};*/
/*class cars{
	public:
		string company;
		string color;

};*/
 /*class cars{
	public:
		string color;
		string company;
};*/
class c1{
	public:
		void add(){
		int x,z;
		cin>>x>>z;
		cout<<x+z<<endl;
		};
		c1 (){
			cout<<"welcome"<<endl;
		}
		~c1 (){
			cout<<"fine";
		}
};
/*class f{
	public:
		void masafat(int a,int b){
			cout<<a-b;
		}
		
};*/
/*class cars{
	private:
		string color;
		
		};
		class c1{
			public:
				int x;
				c1(){
					cout<<"class created";
				}
		};*/
	/*	class point{
			private:
				string color;
			public:	
				point(){
					color="red";
				}
					string cb(){
						color="green";
						return color;
					}
		};*/
		/*class c1{
			public:
			c1(int s){
				cout<<s;
			};
		};*/
int main()
{
      //cout<< "shayan \tsalimi";

     /*int a,b,c,d;
        a=58;
        b=10;
        c=8;
        d=500;
        cout<<a +b;
        cout<<"\n";
        cout<<c *d;
        cout<<"\n";
        cout<<d/b;
        cout<<"\n";
        cout<<b-c;*/

     /* cout<<a+b<<"\n"<<c*d<<"\n"<<d/b<<"\n"<<b-c;*/

     /* string sh;
      string s;
      sh= "shayan";
      s=" salimi";
      cout<<sh<<s;*/

      /*int x;
      cin>>x;
      cout<<x*2;*/

     /* float x,y;
      cin>>x>>y;
      cout<<x+y;*/

      /*string h;
      string b;
      string o;
      cin>>h>>b>>o;
      cout<<h<<"*"<<b<<"**"<<o<<".";*/

     /* int a,b,c;
      cin>>a>>b;
      c=a;
      a=b;
      b=c;
      cout<<a<<"\n"<<b;*/

     /* int x;
      cin>>x;
      if(x>10){
          cout<<"error";
          cout<<x;
      }*/

       
     /*int a,b;
	 cin>>a;
	 if (a==1234){
	 	cin>>b;
	 	cout<<b*3;*/
	 	  
	 	/*string A;
		 cin>>A;
		 if (A=="ADMIN"){
		 	cout<<"welcome";
		 }  */
		 
		/* string A;
		 cin>>A;
		 if(A=="ADMIN"){
		 	cout<<"welcome";
		 }
	 	  else{cout<<"wrong username";}*/
	 	  
	 	  /*int a,b;
	 	  cin>>a>>b;
	 	  if(a>b){
	 	  	cout<<a;
	 	
		   }
		   else{b>a;
		   cout<<b;
		   }*/
		   
		   /*int a;
		   cin>>a;
		   if(a%2==0){
		   	cout<<"even";
		   }
		   else{
		   	cout<<"odd";
		   }*/
		     
		  /* string a;  
		   int b;
		   cin>>a;
		   if(a=="USER"){
		   	cin>>b;
		   
		   	if(b==1234){
		   		cout<<"welcome";
			   }
		else{cout<<"wrong username";
		}   
	}
		 else{cout<<"worng password";
		 }  */

       /* string a,b;
        	cin>>a>>b;
        if((a=="ADMIN")&&(b=="0000")) {
        	cout<<"welcome";
    }
    else {
    	cout<<"error";	
	}*/
		
		
	/*string a;
	cin>>a;
	if((a=="ADMIN")||(a=="admin")){
		cout<<"welcome";
	}	
	 else {
	 	cout<<"error";
	 }*/
	    
	/*string u;
	int p;
	cout<<"please enter your username:";
	   	cin>>u>>p;
    if((u=="admin")||(u=="ADMIN")&&(p==123456)){
        cout<<"welcome";
    }
    else {
    	cout<<"error";
	}*/
	
	/*int a,b,c;
	cin>>a>>b;
	c=pow(a,b);
	cout<<c;*/
	
	/*int n;
	n=-1;
	while(n<=100){
		cout<<n<<"\n";
		n++;
		
	}*/
	
	/*int n;
	n=51;
	while(n<150){
		cout<<n<<"\n";
		n++;
	}*/
	
	/*int n;
	n=2;
	while(n<100){
 	   cout<<n;
		n=n+2;
}*/
	/*int a;
	a=2;
	while(a<=100){
		if(a%2==0)
		cout<<a;
		a++;
	}*/
	
	/*int a;
	a=100;
	while(a<=1000){
		if(a%5==0)
		cout<<a;
		a=a+5;
	}*/
	
	/*int c,b;
	cin>>b;
	c=1;
		while(c<=b){
		cout<<c;
		c++;
}*/

/*string a;
	cin>>a;
	while(a!="exit")
		cin>>a;*/

	/*string a;
	cin>>a;
	while(a==a){
		cin>>a;
	if(a=="exit")
		break;*/
	
	/*string u;
	int p;
	while(true){
		cin>>u>>p;
		if((u=="0")&&(p==0))
			break;
	}*/
	
	/*int n,m;
	m=1;
	while(true){
		cin>>n;
		m=1;
		if(n==0)
		break;
		while(m<=n){
		cout<<m;
		m++;
	}
	}*/	
	
	/*int a,c;
	while(true){
		cin>>a;
		c++;
		if(a==0)
			break;	
	}	
	cout<<c;*/
	/*int i;
for(i=50;i<=100;i++){
	cout<<i;
}*/

/*int i;
for(i=100;i<=200;i=i+2){
	cout<<i;
}*/
/* int a,s;
 s=0;
 for(int i=1;i<=10;i++){
 	cin>>a;
 	s=s+a;
 }
 cout<<s;*/
 
/* int n;
 string s;
 s="*";
 while(true){
 	cin>>n;
 	if(n==0)
 	break;
 	for(int i=1;i<=n;i++)
 	cout<<s;
 }*/
 
 /*int n
 cin>>n;
 for(int s=n;s<=a;s=s-1)
 s=s*n;
 cout<<n;*/
 /*string user,pass;

 while(true){
 
  cin>>user>>pass;
  if((user=="exit")&&(pass=="exit"))
  	break;
  validation (user,pass);
}*/
/*string a;
a=login();
if((a=="ADMIN")||(a=="admin"))
	cout<<"welcome";
else
	cout<<"error";*/
/*while(true){
	string a1;
	int b1,b2,b3,b4;
	cin>>b
}*/	

/*int ss[5]={8,7,6,55,44};
cout<<ss[0]<<" ";
cout<<ss[4];*/

/*float grade[5];
cin>>grade[0]>>grade[1]>>grade[2]>>grade[3]>>grade[4];*/

/*int ss[15]
for(int i=0;i<=14;i++){

	cin>>ss[i];
	}
		for(int p;p<=14;p++{
			cout<<"	"<<ss[p];
}*/

/*int ss[10];
for(int i=0;i<=9;i++){
	cin>>ss[i];
}
	for(int i=0;i<=9;i++){
		if(ss[i]>10)
		cout<<ss[i];	
}*/

/*string ss[10];
int s;
s=0;
for(int i=0;i<=9;i++){
	cin>>ss[i];
}
for(int i=0;i<9;i++){
	if(ss[i]=="mazyiar")
	s++;
}
	cout<<s;*/

/*string ss[10];
string s1;
for(int i=0;i<=9;i++){
	cin>>ss[i];
}
cin>>s1;
for(int i=0;i<=9;i++){
	if(ss[i]==s1)
		break;
	else
	cout<<"not found";

}
cout<<"found";*/
/*int i,min1;
int ss[5];
for(i=0;i<5;i++){
	cin>>ss[i];
}
min1=ss[0];
for(i=1;i<5;i++){
	if(ss[i]<min1){
		min1=ss[i];
	}
}
cout<<min1;*/

/*int ar[2][3]={{2,5,3},{2,1,0}};
cout<<ar[1][2];*/
/*int ar[2][3]={{2,5,3},{2,1,0}};
int ss[3];
//ar[0][0]=ss[2];
ss[0]=ar[0][0];
ss[1]=ar[0][1];
ss[2]=ar[0][2];
for(int i=0;i<3;i++){
	cout<<ss[i];
}*/
/*int ar[2][3]={{5,0,1},{2,0,4}};
for(int i=0;i<2;i++)
	for(int j=0;j<3;j++)
		cout<<ar[i][j];*/

/*int ar[2][3]={{5,0,1},{2,0,4}};
for(int i=0;i<2;i++){
	for(int j=0;j<3;j++){
		cout<<ar[i][j];
	}
		cout<<endl;
}*/
/*int ar[2][3]={{2,5,3},{2,1,0}};
int ss[3];
int sb[3];
ss[0]=ar[0][0];
ss[1]=ar[0][1];
ss[2]=ar[0][2];
for(int i=0;i<3;i++){
	cout<<ss[i];
}
sb[0]=ar[1][0];
sb[1]=ar[1][1];
sb[2]=ar[1][2];
for(int j=0;j<3;j++){
	cout<<sb[j];
}*/
/*int ar[2][3]={{2,5,3},{2,1,0}};
int ar1[3];
int ar2[3];
for(int i=0;i<2;i++){
	for(int j=0;j<3;j++){
		if(i==1)
		ar1[j]=ar[i][j];
		else
		ar2[j]=ar[i][j];
}
cout<<ar[]
}*/

/*int ar[2][2];
int ar1 [2][2];
int ar2 [2][2];
cout<<"please enter first numbers:"<<endl;
for(int i=0;i<2;i++){
	for(int j=0;j<2;j++)
		cin>>ar[i][j];
	}
		cout<<"please enter second numbers:"<<endl;
for(int i=0;i<2;i++){
	for(int j=0;j<2;j++)
	cin>>ar1[i][j];
}
for(int i=0;i<2;i++){
	for(int j=0;j<2;j++)
		ar2[i][j]=ar[i][j]+ar1[i][j];	
}
for(int i=0;i<2;i++){
	for(int j=0;j<2;j++)
		cout<<ar2[i][j]<<"\t";
}*/

/* ar[3][3];
int x=0;
int i,j;
for(i=0;i<3;i++){
	for(j=0;j<3;j++)
		cin>>ar[i][j];
		x=x+ar[i][j];
	}
/*(i=0;i<3;i++){
	for(j=0;j<3;j++)
	
}
cout<<x;*/

/*int ar[3][3];
int a[3];
int b[3];
int c[3];
int i,j;
for(i=0;i<3;i++){
	for(j=0;j<3;j++)
		cin>>ar[i][j];
	}
for(i=0;i<3;i++){
	for(j=0;j<3;j++)
		if(j==0)
			a[i]=ar[i][0];
		if(j==1)
			b[i]=ar[i][1];
		if(j==2)
			c[i]=ar[i][2];
}

for(i=0;i<3;i++){
	cout<<a[i]<<"\t";
for(i=0;i<3;i++)
	cout<<b[i]<<"\t";
for(i=0;i<3;i++)
	cout<<c[i]<<"\t";
}*/

/*int ar[5]={0,2,3,1,8};
f1 (ar,5);*/

/*int ar[5]={0,2,3,1,8};
f1(ar,5);
cout<<ar[0];*/

/*int ar[5]={0,2,3,1,8};
cout<<ar;*/
/*int ar[5];
for (int i=0;i<5;i++)
cin>>ar[i];
f1(ar,5);
for (int i=0;i<5;i++)
cout<<ar[i];*/

/*int ar[3][3];
f1(ar);
for(int i=0;i<3;i++)
	for(int j=0;j<3;j++)
		cin>>ar[i][j];
		f1(ar);
	for(int i=0;i<3;i++)
		for(int j=0;j<3;j++)
		cout<<ar[i][j]<<" ";*/

/*int a=10;
cout<<&a;*/
/*int a=10;
int *p;
p=&a;
//cout<<p;
cout<<*p;*/

/*int ss[3][3];
for(int i=0;i<3;i++)
	for(int j=0;j<3;j++)
		cin>>ss[i][j];
	for(int i=0;i<3;i++)
		for(int j=0;j<3;j++)
		
		if(ss[0][0]<ss[0][1])
		
		 
		
	for(int i=0;i<3;i++)
		for(int j=0;j<3;j++)	
		cout<<ss[i][j];*/
		
/*int a=2;
int *p;
p=&a;
cout<<*p;*/		
		
/*int a=2;
int*p,*q;
p=&a;
//cout<<*p;		
q=p;
cout<<*p;
cout<<p;*/		

/*int x=5;
cout<<sizeof(x);
cout<<endl;
float b;
cout<<sizeof(b);
cout<<endl;
char a='c';
cout<<sizeof(a);
cout<<endl;
string d="damn";
cout<<sizeof(d);
cout<<endl;
long int m=5;
cout<<sizeof(m);*/

/*int x[2];
cout<<sizeof(x);*/

/*int s=10;
int *p;
p=&s;
cout<<p<<endl;
p++;
cout<<p;*/
	
/*int ar[4]={0,5,2,1};
int *p;
p=ar;
cout<<p<<endl;
cout<<*p;*/

/*int ss[10];
int *p;
p=ss;
for(int i=0;i<10;i++){
	cin>>ss[i];
}
for(int i=0;i<10;i++){
	cout<<*p<<"\t";
	p++;
}*/

/*int ss[10];
int *p;
p=ss;
p=p+9;
for(int i=0;i<10;i++){
	cin>>ss[i];
}
for(int i=0;i<10;i++){
	cout<<*p<<"\t";
	p--;
}*/

/*int first[3][3];
int second[3][3];
cout<<"Enter first numbers:"<<endl;
for(int i=0;i<3;i++){
	for(int j=0;j<3;j++)
	cin>>first[i][j];
}
cout<<"Enter second numbers:"<<endl;
for(int i=0;i<3;i++){
	for(int j=0;j<3;j++)
	cin>>second[i][j];
}
display(first,second);
for(int i=0;i<3;i++)
	for(int j=0;j<3;j++)
	cout<<first[i][j]<<" ";
	cout<<endl;
for(int i=0;i<3;i++)
	for(int j=0;j<3;j++)
	cout<<second[i][j]<<" ";*/
	
	
/*int aa[10],bb[10],cc[10],i;
int *p,*x;
p=aa,x=bb;
for(i=0;i<10;i++){
    cin>>aa[i];
}
for(i=0;i<10;i++){
    cin>>bb[i];
}
for (i=0;i<10;i++){
cc[i]=*x+*p;
p++;
x++;
}
for (i=0;i<10;i++){
    cout<<cc[i]<<" ";
}*/

/*c1 obj1;
obj1.mt1();*/

/*c1 obj2;
obj2.mt2();*/

/*c1 obj1,obj2,obj3,obj4;
obj1.mt1();
obj2.mt1();
obj3.mt1();
obj4.mt1();*/  

/*cout<<"Select an operation:"<<endl<<"1.add    2.differ"<<endl<<"I want ";
	cin>>display1;
	cout<<"-------------------"<<endl;
	if(display1=="add"){
		project adding1;
		adding1.add();
	}
	if(display1=="differ"){
		project differing2;
		differing2.differ();
	}
	if((display1!="add")&&(display1!="differ")){
		project failed3;
		failed3.error();
	}*/

/*cars benz;
benz.company="benz";*/

/*cars honda;
honda.company="honda";
honda.color="red";
cout<<honda.company<<endl<<honda.color;*/ 

/*int a,b;
cin>>a>>b;
f benz;
benz.masafat(a,b);*/
                   
/*cars benz;
benz.color="red"; */

//c1 obj1;
 /*point obj;
 string s=obj.cb();
 cout<<s; */
 //c1 obj(12);  
 /*c1 obj1;
 obj1.add();*/
 //string f;
 //ofstream f1ss ("D:\\z.dat");
   
/*ofstream f1ss ("C:\\z.dat");  
if(!f1ss){
	cout<<"error";
	exit(0);
}   */
/*string s;
cin>>s;
ofstream f1ss ("D:\\z.dat");  
if(!f1ss){
	cout<<"error";
	exit(0);
}   
f1ss<<s;
f1ss.close();*/
 
/*string s,f;
ofstream s1 ("D:\\z.dat");
if(!s1){
	cout<<"error";
	exit(0);
}
while(true){
cin>>s;
if(s=="exit")
break;
	s1<<s<<endl;
	
}
s1.close();*/
string s;
ifstream s1("D:\\z.dat");
s1>>s;
while(!s1.eof()){
cout<<s;
cout<<endl;
s1>>s;
}
s1.close();

	 	return 0;  
}
/*void display(int ss[][3],int tt[][3]){
	cout<<"Enter additional number:"<<endl;
	int z;
	cin>>z;
	cout<<endl;
	for(int i=0;i<3;i++)
		for(int j=0;j<3;j++)
		if(ss[i][j]==z)
			ss[i][j]=0;
	for(int i=0;i<3;i++)
		for(int j=0;j<3;j++)
		if(tt[i][j]==z)
			tt[i][j]=0;
	}*/

/*void f1(int br[][3]){
for(int i=0;i<3;i++)
	for(int j=0;j<3;j++)
		if(br[i][j]>5)
			br[i][j]=0;
}*/

/*void f1 (int br [],int x){
	br[0]=99;
}*/

/*void f1(int br[],int x){
	for (int i=0;i<x;i++)
	br[i]=br[i]*2;
	
}*/
/*void f1 (int br [],int x){
	for (int i=0;i<x;i++)
	cout<<br[i]<<"\t";
}*/
/*void validation (string user,string pass){
 	if((user=="ADMIN")&&(pass=="0000"))
 		cout<<"welcome";
	else
		cout<<"error";
}*/
/*string login (){
	string b;
	cin>>b;
	return b;
}*/



       
       
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       

 